#!/bin/bash

# AquaRandom Deployment Script
# This script deploys the serverless backend using AWS SAM

set -e

# Configuration
AWS_PROFILE="${AWS_PROFILE:-personal}"
AWS_REGION="${AWS_REGION:-us-east-1}"
STACK_NAME="aquarandom-backend"

echo "==================================="
echo "AquaRandom Deployment Script"
echo "==================================="
echo "AWS Profile: $AWS_PROFILE"
echo "AWS Region: $AWS_REGION"
echo "Stack Name: $STACK_NAME"
echo ""

# Check if AWS SAM CLI is installed
if ! command -v sam &> /dev/null; then
    echo "ERROR: AWS SAM CLI is not installed."
    echo "Install it with: brew install aws-sam-cli"
    exit 1
fi

# Check if AWS CLI is configured
if ! AWS_PROFILE=$AWS_PROFILE aws sts get-caller-identity &> /dev/null; then
    echo "ERROR: AWS credentials not configured for profile '$AWS_PROFILE'"
    echo "Run: aws configure --profile $AWS_PROFILE"
    exit 1
fi

echo "Step 1: Installing Lambda dependencies..."
cd lambda
npm install --production
cd ..

echo ""
echo "Step 2: Building SAM application..."
sam build --profile $AWS_PROFILE

echo ""
echo "Step 3: Deploying to AWS..."
sam deploy \
    --stack-name $STACK_NAME \
    --capabilities CAPABILITY_IAM \
    --region $AWS_REGION \
    --profile $AWS_PROFILE \
    --resolve-s3 \
    --no-confirm-changeset \
    --no-fail-on-empty-changeset

echo ""
echo "Step 4: Getting API Gateway URL..."
API_URL=$(AWS_PROFILE=$AWS_PROFILE aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --region $AWS_REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
    --output text)

echo ""
echo "==================================="
echo "Deployment Complete!"
echo "==================================="
echo ""
echo "API Gateway URL: $API_URL"
echo ""
echo "IMPORTANT: Update your frontend config with this URL!"
echo ""
echo "Edit public/config.js and set:"
echo "  window.AQUARANDOM_API_URL = '$API_URL';"
echo ""
echo "Then commit and push to trigger Amplify deployment:"
echo "  git add ."
echo "  git commit -m 'Update API URL for production'"
echo "  git push"
echo ""

# Optionally update the config file automatically
read -p "Do you want to automatically update public/config.js? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cat > public/config.js << EOF
// AquaRandom Configuration
// Auto-generated by deploy.sh on $(date)

(function() {
  if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    window.AQUARANDOM_API_URL = '';
  } else {
    window.AQUARANDOM_API_URL = '$API_URL';
  }
})();
EOF
    echo "public/config.js has been updated!"
    echo ""
    echo "Now commit and push:"
    echo "  git add ."
    echo "  git commit -m 'Update API URL for production'"
    echo "  git push"
fi

